services:
  - type: web
    name: tradingbuddy
    env: python
    region: singapore        
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn service:app --preload --timeout 200"
    autoDeploy: true
    envVars:
      PYTHON_VERSION: 3.11
